# SPRINT 9 - Nociones y conocimientos básicos de Python

 RAFAEL FONS BIBILONI

NIVEL 1

In [1]:
## Ejercicio 1

# Calculadora del índice de masa corporal
# IMC es necesario dividir el peso en kg de un paciente entre el cuadrado de su altura en metros

def IMC(peso, altura):
    """Esta función calcula el IMC (indice de masas corporal),
    en base a dos parámetros:
        peso, expresado en Kg.
        y altura, expresado en metros.
     """
    
    if not isinstance(peso, (float,int)):
        print("formato peso erroneo")
        return
    elif not isinstance(altura, (float,int)):
        print("formato altura erroneo")
        return
    elif peso<0:
        print("El peso tiene que ser mayor a cero")
        return
    elif altura<0:
        print("La altura tiene que ser mayor a cero")
        return
    else:
        imc = round(peso/(altura**2),2)
    
    if imc <=18.5:
       print(f"El IMC es", imc, " -bajo peso-") 
    elif imc <=24.9:
       print(f"El IMC es", imc, " -peso normal-") 
    elif imc <=29.9:
       print(f"El IMC es", imc, " -sobrepeso-")
    elif imc >29.9:
       print(f"El IMC es", imc, " -obecidad-")
    else:
        print("los paramtros son inorrectos")

In [2]:
IMC(79, 1.78)

El IMC es 24.93  -sobrepeso-

In [ ]:
## Ejercicio 2

# Conversor de temperaturas
# Las mas comunes son Celsius (°C), Fahrenheit (°F) y Kelvin (K).

def conversor_temp(*arg):
    
    # Verificación de temp ingresado
    while True:                                         #ejecuta el bucle infinito, SI O SI HAY QUE PONER UN BREAK
        temp = input("Ingrese el valor de la temperatura: C=Celsius, F=Fahrenheit y, K=Kelvin")
        try:                                            #en caso de que algo falle (el float no se puede ejcutar), el script continua
            temp = float(temp)
            if temp < 0:
                print("Error. El valor debe ser mayor o igual a cero. Intente nuevamente.\n")
                continue
            break                                       # si llegó aquí, la entrada es válida y sale del bucle
        except ValueError:
            print(f"La'{temp}' no es un valor numérico válido. Intente nuevamente.\n")
    
    # verificacion de unidad de temp ingresados
    unid_temp = input("Ingrese la unidad de temperatura: C=Celsius, F=Fahrenheit y, K=Kelvin").upper()
    while unid_temp not in ("C", "F", "K"):
        print(f"\nHa ingresado ", unid_temp," como unidad de temperatura, lo cual es incorrecto.\nRecuerde que debe ingresar la primer letra, C=Celsius, F=Fahrenheit y, K=Kelvin") 
        unid_temp = input("\nIngrese nuevamente la unidad de la temperatura").upper()
    
    # verificacion de unidad de temp a convetir
    while True:
        convert_to = input("Ingrese la unidad de temperatura a convertir: C=Celsius, F=Fahrenheit y, K=Kelvin").upper()
        try:
            if convert_to in ("C", "F", "K"):
                if unid_temp == convert_to:
                    print("Error, ha solictado convertir la temperaura a la misma unidad")
                else:
                    break
            else:
                print(f"\nHa ingresado ", convert_to," como unidad de temperatura a convertir, lo cual es incorrecto.\nRecuerde que debe ingresar la primer letra, C=Celsius, F=Fahrenheit y, K=Kelvin") 
                convert_to = input("\nIngrese nuevamente la unidad de la temperatura para convertir").upper()   
        except ValueError:
            print(f"La temperatura {convert_to}' no es valor válido. Intente nuevamente.\n")
    
    # mensaje que resume los parametros ingresados:
    print(f"\nLa temperatura ingresada es: ", temp, unid_temp, "-> Se convertirá a ",convert_to)
    
    # calculo de conversiones
    match unid_temp:
        case "C":
            match convert_to:
                case "F": temp_convert = (temp * 9/5) + 32
                case "K": temp_convert = (temp +273.15)
        case "F":
            match convert_to:
                case "C": temp_convert = (temp -32) * 5/9
                case "K": temp_convert = ((temp -32) * 5/9 ) +273.15
        case "K":
            match convert_to:
                case "C": temp_convert = (temp -273.15)
                case "F": temp_convert = ((temp -273.15) -32) * 5/9       
    
    return print(round(temp_convert,1),convert_to)

In [43]:
conversor_temp()

Error, ha solictado convertir la temperaura a la misma unidad

La temperatura ingresada es:  40.0 F -> Se convertirá a  K
277.6 K

In [ ]:
# Ejercicio 2
# EXTRA: usar diccionarios para alamcen de funciones y combinaciones de conversion

def conversor_temp_DICC(*arg):
    
    # Verificación de temp ingresado
    while True:                                         #ejecuta el bucle infinito, HAY QUE PONER UN BREAK
        temp = input("Ingrese el valor de la temperatura: C=Celsius, F=Fahrenheit y, K=Kelvin")
        try:
            temp = float(temp)
            if temp < 0:
                print("ERROR: El valor debe ser mayor o igual a cero. Intente nuevamente.\n")
                continue
            break                                       # si llegó aquí, la entrada es válida y sale del bucle
        except ValueError:
            print(f"La'{temp}' no es un valor numérico válido. Intente nuevamente.\n")
    
    # verificacion de unidad de temp ingresados
    base_temp = input("Ingrese la unidad de temperatura: C=Celsius, F=Fahrenheit y, K=Kelvin").upper()
    while base_temp not in ("C", "F", "K"):
        print(f"\nHa ingresado ", base_temp," como unidad de temperatura, lo cual es incorrecto.\nRecuerde que debe ingresar la primer letra, C=Celsius, F=Fahrenheit y, K=Kelvin") 
        base_temp = input("\nIngrese nuevamente la unidad de la temperatura").upper()
    
    # verificacion de unidad de temp a convetir
    while True:
        convert_to = input("Ingrese la unidad de temperatura a convertir: C=Celsius, F=Fahrenheit y, K=Kelvin").upper()
        try:
            if convert_to in ("C", "F", "K"):
                if base_temp == convert_to:
                    print("Error, ha solictado convertir la temperaura a la misma unidad")
                else:
                    break
            else:
                print(f"\nHa ingresado ", convert_to," como unidad de temperatura a convertir, lo cual es incorrecto.\nRecuerde que debe ingresar la primer letra, C=Celsius, F=Fahrenheit y, K=Kelvin") 
                convert_to = input("\nIngrese nuevamente la unidad de la temperatura para convertir").upper()   
        except ValueError:
            print(f"La temperatura {convert_to}' no es valor válido. Intente nuevamente.\n")
    
    # mensaje que resume los parametros ingresados:
    print(f"\nLa temperatura ingresada es: ", temp, base_temp, "-> Se convertirá a ",convert_to)
        

    # calculo de conversiones usando un diccionario:
     
    def c_to_f(temp):
            return (temp * 9/5) + 32
        
    def c_to_k(temp):
            return (temp +273.15)

    def f_to_c(temp):
            return (temp -32) * 5/9
        
    def f_to_k(temp):
            return  ((temp -32) * 5/9 ) +273.15
        
    def k_to_c(temp):
            return (temp -273.15)
        
    def k_to_f(temp):
            return((temp -273.15) -32) * 5/9 
    
    conversiones = {
            ("C","F") : c_to_f,
            ("C","K") : c_to_k,
            ("F","C") : f_to_c,
            ("F","K") : f_to_k,
            ("K","C") : k_to_c,
            ("K","F") : k_to_f
        }
    
    return conversiones[(base_temp, convert_to)](temp)

In [51]:
conversor_temp_DICC()

Error, ha solictado convertir la temperaura a la misma unidad

La temperatura ingresada es:  40.0 K -> Se convertirá a  F

-147.30555555555554

In [ ]:
# NIVEL 1 - Ejecricio 3

# Contador de palabras: escribe una función que dado un texto, muestre las veces que aparece cada palabra.
# Intenta que se gestionen todas las posibles casuísticas que hagan que el programa no funcione correctamente.


def contar_palabr(*arg):

    print("Ingrese una frase a analizar")
    
    #frase = "pablito clavo un clavito, que clavito clavo pablito"
    frase = input("Ingrese una frase a analizar")
    
    
    #palabra = "cLavo"
    palabra = input("Ingrese la palabra que desea contar")
    
    print(f"Ha ingresado: ´",frase,"´\nQuiere contar las veces que sale la siguiente palabra:", palabra)
    
    lista_palabras = frase.split()

    contador = 0
    for elemento in lista_palabras:
        if palabra.upper() == elemento.upper():
            contador += 1

    return print(f"\nLa palabra buscada -{palabra}- aparece:",contador,"vez/veces")

In [ ]:
contar_palabr()

Ingrese una frase a analizar
Ha ingresaso: ´ pablo pablo.   caca ´
Quiere contar las veces que sale la siguiente palabra: perro

La palabra buscada -perro- aparece: 0 vez/veces

In [149]:
# NIVEL 1 - Ejecricio 3
# 
# (EXTRA): ¿Cuál es la longitud media de las palabras del texto que has escrito?
# Por ejempli: “¿Hola cómo va?” debería devolver (4+4+2) / 3 = 3.33 contador de palabras

def long_prom_palabr(*arg):

    print("Ingrese una frase a analizar")
    frase = "pablito clavo un clavito, que clavito clavo pablito"
    #frase = input("Ingrese una frase a analizar")

    lista_palabras = frase.split()
    longitud =[]

    contador = 0
    for elemento in lista_palabras:
        for letra in elemento:
            contador += 1
        longitud.append(contador)
        contador = 0
       
    print(f"Ha ingresaso la frase: ´",frase,"´\nLa longitud de las palabras es la siguiente:")
    for i in range(len(longitud)):
        if i==0:
            print("(", end="")
        if i != (len(longitud)-1):
                print(longitud[i],end="+")
                i=+1
        else:
                long_prom = round(sum(longitud)/len(longitud),1)
                print(longitud[i], end=") /")
                print(len(longitud),end=" = ")
                print(long_prom, end="")

In [150]:
long_prom_palabr()

Ingrese una frase a analizar
Ha ingresaso la frase: ´ pablito clavo un clavito, que clavito clavo pablito ´
La longitud de las palabras es la siguiente:
(7+5+2+8+3+7+5+7) /8 = 5.5

In [237]:
# Nivel 1 - Ejercicio 4

# Diccionario inverso (con posibilidad de duplicados)
# Resulta que el cliente tiene una encuesta muy antigua que se almacena en un diccionario y los resultados los necesita a la inversa,
# es decir, intercambiando las claves y valores. 

encuesta = {
    "a":"pepe",
    "b":"no lo se",
    "c":7
}

def invertir_dicc(diccionario):
    claves = list(diccionario.keys())
    dicc_invertido ={}
    for i in range(len(diccionario)):
        dicc_invertido[diccionario[claves[i]]] = claves[i]

    return dicc_invertido

In [238]:
print(encuesta)
invertir_dicc(encuesta)

{'a': 'pepe', 'b': 'no lo se', 'c': 7}

{'pepe': 'a', 'no lo se': 'b', 7: 'c'}

In [297]:
# EXTRA: Los valores y claves en el diccionario original son únicos; si éste no es el caso, 
# la función debería imprimir un mensaje de advertencia, junto con una lista con los valores asociados a la clave repetida.

encuesta_repetidos = {
    "z":7,
    "a":"pepe",
    "b":"no lo se",
    "c":7,
    "d":7
}
print("El diccionario original es:",encuesta_repetidos)

def inv_dicc_rep(diccionario):

    dicc_invertido = {}
    
    # verificar si los "valores" del diccionario estan duplicados, y en ese caso guardar esto en un nuevo diccionario
    
    for clave, valor in diccionario.items():                # el metodo items() devuele tuplas
        if valor not in dicc_invertido:
            dicc_invertido[valor] = [clave]   # primera vez, invierto el orden valor, clave
        else:
            dicc_invertido[valor].append(clave)  # ya existe, agrego la nueva clave
    return print("\nEl nuevo diccionario invertido es:", dicc_invertido)

El diccionario original es: {'z': 7, 'a': 'pepe', 'b': 'no lo se', 'c': 7, 'd': 7}

In [298]:
inv_dicc_rep(encuesta_repetidos)

El nuevo diccionario invertido es: {7: ['z', 'c', 'd'], 'pepe': ['a'], 'no lo se': ['b']}

## NIVEL 2

In [21]:
# NIVEL 2 - Ejercicio 1

## leemos el archivo .txt primero:

with open("/Users/rafafons/Library/Mobile Documents/com~apple~CloudDocs/2_Rafa/01-Capacitaciones/IT Academy/sprint 9/tu me quieres blanca.txt",
          "r") as archivo:
    texto = archivo.read()
print(texto)

Tú me quieres alba,
me quieres de espumas,
me quieres de nácar.
Que sea azucena
Sobre todas, casta.
De perfume tenue.
Corola cerrada .

Ni un rayo de luna
filtrado me haya.
Ni una margarita
se diga mi hermana.
Tú me quieres nívea,
tú me quieres blanca,
tú me quieres alba.

Tú que hubiste todas
las copas a mano,
de frutos y mieles
los labios morados.
Tú que en el banquete
cubierto de pámpanos
dejaste las carnes
festejando a Baco.
Tú que en los jardines
negros del Engaño
vestido de rojo
corriste al Estrago.

Tú que el esqueleto
conservas intacto
no sé todavía
por cuáles milagros,
me pretendes blanca
(Dios te lo perdone),
me pretendes casta
(Dios te lo perdone),
¡me pretendes alba!

Huye hacia los bosques,
vete a la montaña;
límpiate la boca;
vive en las cabañas;
toca con las manos
la tierra mojada;
alimenta el cuerpo
con raíz amarga;
bebe de las rocas;
duerme sobre escarcha;
renueva tejidos
con salitre y agua:

Habla con los pájaros
y lévate al alba.
Y cuando las carnes
te sean tornadas,
y cuando hayas puesto
en ellas el alma
que por las alcobas
se quedó enredada,
entonces, buen hombre,
preténdeme blanca,
preténdeme nívea,
preténdeme casta.

In [ ]:
# hacemos la funcion para contar palabras y hacer el diccionario

import string                   # me sirve para importar el abecedario en lugar de escribirlo

def contar_palabras_por_letra(texto):    
    # Limpiar el texto
    caracteres_limpios = []
    for ch in texto:
        if ch.isalpha():                        # esta funcion = True si el caracter es: a-z, ñ, á, etc.). Quito signo de puntuación
            caracteres_limpios.append(ch.lower())
        else:
            caracteres_limpios.append(" ")
    limpio = "".join(caracteres_limpios)        # genero un string uniendo los caracteres limpios y en minúsculas
    
    palabras = limpio.split()                   # separo las palabras en una lista
    
    # Diccionario principal: letra -> otro diccionario
    frecuencia = {}
    for letra in string.ascii_lowercase:        # importo el abecedario en minúscula
        frecuencia[letra] = {}                  #creo un diccionario vacío por cada letra del abecedario
        
    # Contar 
    for palabra in palabras:
        ch_inicial = palabra[0]                 # caracter inicial de cada palabra 
        # Si la palabra ya está, le sumamos 1
        if palabra in frecuencia[ch_inicial]:
            frecuencia[ch_inicial][palabra] += 1
        else:
            # Si es la primera vez que aparece, la inicializamos con 1
            frecuencia[ch_inicial][palabra] = 1
    
    # Ordenar el diccionario final 
    resultado = {}
    for ch_inicial in frecuencia.keys():            # no la ordeno porque se creo ya ordenada usando string
        if frecuencia[ch_inicial]:
            # Ordenamos las palabras dentro de cada ch_inicial
            resultado[ch_inicial] = dict(sorted(frecuencia[ch_inicial].items()))
    
    return resultado

In [41]:
contar_palabras_por_letra(texto)

{'a': {'a': 3,
  'agua': 1,
  'al': 2,
  'alba': 4,
  'alcobas': 1,
  'alimenta': 1,
  'alma': 1,
  'amarga': 1,
  'azucena': 1},
 'b': {'baco': 1,
  'banquete': 1,
  'bebe': 1,
  'blanca': 3,
  'boca': 1,
  'bosques': 1,
  'buen': 1},
 'c': {'cabañas': 1,
  'carnes': 2,
  'casta': 3,
  'cerrada': 1,
  'con': 4,
  'conservas': 1,
  'copas': 1,
  'corola': 1,
  'corriste': 1,
  'cuando': 2,
  'cubierto': 1,
  'cuerpo': 1,
  'cuáles': 1},
 'd': {'de': 8, 'dejaste': 1, 'del': 1, 'diga': 1, 'dios': 2, 'duerme': 1},
 'e': {'el': 4,
  'ellas': 1,
  'en': 4,
  'engaño': 1,
  'enredada': 1,
  'entonces': 1,
  'escarcha': 1,
  'espumas': 1,
  'esqueleto': 1,
  'estrago': 1},
 'f': {'festejando': 1, 'filtrado': 1, 'frutos': 1},
 'h': {'habla': 1,
  'hacia': 1,
  'haya': 1,
  'hayas': 1,
  'hermana': 1,
  'hombre': 1,
  'hubiste': 1,
  'huye': 1},
 'i': {'intacto': 1},
 'j': {'jardines': 1},
 'l': {'la': 3,
  'labios': 1,
  'las': 7,
  'lo': 2,
  'los': 4,
  'luna': 1,
  'lévate': 1,
  'límpiate': 1},
 'm': {'mano': 1,
  'manos': 1,
  'margarita': 1,
  'me': 10,
  'mi': 1,
  'mieles': 1,
  'milagros': 1,
  'mojada': 1,
  'montaña': 1,
  'morados': 1},
 'n': {'negros': 1, 'ni': 2, 'no': 1, 'nácar': 1, 'nívea': 2},
 'p': {'perdone': 2,
  'perfume': 1,
  'por': 2,
  'pretendes': 3,
  'preténdeme': 3,
  'puesto': 1,
  'pájaros': 1,
  'pámpanos': 1},
 'q': {'que': 6, 'quedó': 1, 'quieres': 6},
 'r': {'rayo': 1, 'raíz': 1, 'renueva': 1, 'rocas': 1, 'rojo': 1},
 's': {'salitre': 1, 'se': 2, 'sea': 1, 'sean': 1, 'sobre': 2, 'sé': 1},
 't': {'te': 3,
  'tejidos': 1,
  'tenue': 1,
  'tierra': 1,
  'toca': 1,
  'todas': 2,
  'todavía': 1,
  'tornadas': 1,
  'tú': 8},
 'u': {'un': 1, 'una': 1},
 'v': {'vestido': 1, 'vete': 1, 'vive': 1},
 'y': {'y': 5}}

In [92]:
## # NIVEL 2 - Ejercicio 2

# Conversión de tipos de datos.

# El cliente recibe una lista de datos y necesita generar dos listas, la primera donde estarán todos los elementos que
# pudieron convertirse en flotantes y la otra donde están los elementos que no pudieron convertirse.

lista = [ '1.3', 'one' , '1e10' , 'seven', '3-1/2', ('2',1,1.4,'not-a-number'), [1,2,'3','3.4']]
lista

type(lista[6])

#len(lista[5])

list

In [100]:
def conversor_to_float(lista):
    # recorremos los elementos y hacemos una lista
    lista_float = []
    lista_no_float = []

    for elem in lista:
        # si el elemento es una lista o tupla
        if isinstance(elem, (list, tuple)):
            for sub_elem in elem:
                try:
                    lista_float.append(float(sub_elem))
                except:
                    lista_no_float.append(sub_elem)

        # si el elemento es un valor normal
        else:
            try:
                lista_float.append(float(elem))
            except:
                lista_no_float.append(elem)

    return lista_float, lista_no_float

In [101]:
conversor_to_float(lista)

([1.3, 10000000000.0, 2.0, 1.0, 1.4, 1.0, 2.0, 3.0, 3.4],
 ['one', 'seven', '3-1/2', 'not-a-number'])

## NIVEL 3

In [ ]:
# NIVEL 3 - Ejercicio 1

#  Generador de Contraseñas:

# La función debe depender de los siguientes parámetros:
    # longitud (int): Longitud de la contraseña
    # mayúsculas (bool = True): Si tiene que aparecer mayúsculas
    # minúsculas (bool = True): Si tiene que aparecer minúsculas
    # números (bool = True): Si tiene que aparecer números
    # signos (bool = False): Si tiene que aparecer caracteres especiales (,-$? o similares)


# La función tiene que tener la siguiente forma: crear_contraseña(10, True, True, True, True)
# Ademas se debe verificar que cumpla las condiciones

In [132]:
from numpy import random
x = random.rand()
print(x)


random_array = random.randint(1, 5, size=(2,6))
print(random_array)

y = random.choice([1, 2, 3, 4, 5, 10])
print(y)

0.17612133550929332
[[1 2 2 3 1 2]
 [3 1 3 3 1 1]]
4

In [246]:
def crear_contraseña(long, mayus, minus, num, signos):
    """
    # Generador de contraseñas:
    
    longitud (int): Longitud de la contraseña
    mayúsculas (bool = True): Si tiene que aparecer mayúsculas...string.ascii_uppercase
    minúsculas (bool = True): Si tiene que aparecer minúsculas...string.ascii_lowercase
    números (bool = True): Si tiene que aparecer números...string.digits
    signos (bool = False): Si tiene que aparecer caracteres especiales (,-$? o similares)...string.punctuation
    
    """
    
    from numpy import random
    import string
    
    # defino todos los posibles carateres que puedo elegir y los minimos carcateres que se requieren:
    posibles_ch = ""
    unicos_ch = ""              #defino el minimo de cada tipo para asegurar que cumple con los requisitos
    cant_ch_min = 0
    
    if mayus == True:
        cant_ch_min += 1
        posibles_ch += string.ascii_uppercase
        unicos_ch += random.choice(list(string.ascii_uppercase), 1)[0]                  #tengo que indicar el [0] porque numpy genera una lista
    if minus == True:
        cant_ch_min += 1
        posibles_ch += string.ascii_lowercase
        unicos_ch += random.choice(list(string.ascii_lowercase), 1)[0]
    if num == True:
        cant_ch_min += 1
        posibles_ch += string.digits
        unicos_ch += random.choice(list(string.digits), 1)[0]        
    if signos == True:
        cant_ch_min += 1
        posibles_ch += string.punctuation
        unicos_ch += random.choice(list(string.punctuation), 1)[0]
    
    
    # ajusto longitud de contraseña minima segun requisitos:
    if long < (cant_ch_min):
        print("ERROR: la longitud de la contraseña debe ser mayor a 4 caracteres")
    
    else:
        try:
            # unifico los posbles caracteres (minmos segun requisitos + resto de posibles carectares)   
            ch_finales = list( unicos_ch + ''.join(random.choice(list(posibles_ch), (long-cant_ch_min))) )
            
            # desordena la lista
            random.shuffle(ch_finales)             # shuffle no devuelve nada
            
            #uno los caracteres de la lista para obtener un string
            contraseña = ''.join(ch_finales)
            return contraseña 
        
        except:
            print("Los parametros ingresados no son correctos")

In [247]:
crear_contraseña(4, True,True,True,True)

'5=yP'

In [259]:
## NIVEL 3 - Ejercicio 2

# Procesamiento de datos simple

# Una compañera de trabajo nos ha pedido un favor, aprovechando que sabe que estamos aprendiendo a programar. Tiene un
# histórico de partidos de fútbol catalán en un fichero, donde se almacenan los nombres de los equipos y los resultados.
# Necesita que procesemos los datos de forma automática, para extraer los resultados que necesita.

# Necesita un programa que devuelva:

    # El número total de goles que ha marcado cada equipo.
    # El nombre del equipo más goleador.
    # El nombre del equipo más goleado
    # La clasificación global (cada victoria: 3 pts, empate 1 pts, derrota 0 pts)

In [276]:
# Importo el archivo "historic_partits.txt"

import pandas as pd

ruta = "/Users/rafafons/Library/Mobile Documents/com~apple~CloudDocs/2_Rafa/01-Capacitaciones/IT Academy/sprint 9/historic partits.txt"

df_historic_partits = pd.read_csv(ruta, sep="\t", header=None, names=["Local", "Resultado", "Visitante"])
df_historic_partits

                   Local Resultado   Visitante
0                Manlleu       0-1  Granollers
1             Vilafranca       4-5    Terrassa
2                   Olot       5-0  Granollers
3             Vilafranca       5-5     Manlleu
4               Cornellà       5-1        Prat
..                   ...       ...         ...
495  Nàstic de Tarragona       1-3        Olot
496             Badalona       5-4        Prat
497                 Olot       4-5  Llagostera
498         FC Barcelona       3-1    Cornellà
499                 Olot       0-5  Granollers

[500 rows x 3 columns]

In [ ]:
type(df_historic_partits.loc[3,"Resultado"])

# Convierto el campo resultado en 2 columnas de goles
for i in range(0,len(df_historic_partits)):       
    resultado = list(df_historic_partits.loc[i,"Resultado"])

    df_historic_partits.loc[i,"Goles local"] = int(resultado[0])
    df_historic_partits.loc[i,"Goles visitante"] = int(resultado[2])

#analizamos el resultado y colocamos puntajes
for i in range(0,len(df_historic_partits)):       
    # Caso 1: partidos ganados por local
    if df_historic_partits.loc[i,"Goles local"] > df_historic_partits.loc[i,"Goles visitante"]:
        df_historic_partits.loc[i,"Puntos local"] = 3
        df_historic_partits.loc[i,"Puntos visitante"] = 0
    #caso 2: partidos empatados
    elif df_historic_partits.loc[i,"Goles local"] == df_historic_partits.loc[i,"Goles visitante"]:
        df_historic_partits.loc[i,"Puntos local"] = 1
        df_historic_partits.loc[i,"Puntos visitante"] = 1
    #caso 3: partidas perdidos por local
    elif df_historic_partits.loc[i,"Goles local"] < df_historic_partits.loc[i,"Goles visitante"]:
        df_historic_partits.loc[i,"Puntos local"] = 0
        df_historic_partits.loc[i,"Puntos visitante"] = 3    

df_historic_partits

,Local,Resultado,Visitante,Goles local,Goles visitante,Puntos local,Puntos visitante
0,Manlleu,0-1,Granollers,0,1,0.0,3.0
1,Vilafranca,4-5,Terrassa,4,5,0.0,3.0
2,Olot,5-0,Granollers,5,0,3.0,0.0
3,Vilafranca,5-5,Manlleu,5,5,1.0,1.0
4,Cornellà,5-1,Prat,5,1,3.0,0.0
...,...,...,...,...,...,...,...
495,Nàstic de Tarragona,1-3,Olot,1,3,0.0,3.0
496,Badalona,5-4,Prat,5,4,3.0,0.0
497,Olot,4-5,Llagostera,4,5,0.0,3.0
498,FC Barcelona,3-1,Cornellà,3,1,3.0,0.0
499,Olot,0-5,Granollers,0,5,0.0,3.0

In [ ]:
# hago 2 tablas con los datos por equipo x fila (local y viistante) y luego las concateno 

locales = df_historic_partits[["Local", "Resultado", "Visitante", "Goles local", "Goles visitante", "Puntos local"]]
locales = locales.rename(columns={"Local":"Equipo", "Visitante":"Rival", "Goles local":"Goles convertidos",
                                  "Goles visitante": "Goles recibidos", "Puntos local":"Puntos"})

#calculo la cantidad de partidos ganados, empatados y perdidos
for i in range(0,len(locales)):       
    # Caso 1: partidos ganados por local
    if locales.loc[i,"Goles convertidos"] > locales.loc[i,"Goles recibidos"]:
        locales.loc[i,"Ganados"] = 1
    #caso 2: partidos empatados
    elif locales.loc[i,"Goles convertidos"] == locales.loc[i,"Goles recibidos"]:
        locales.loc[i,"Empatados"] = 1
    #caso 3: partidas perdidos por local
    elif locales.loc[i,"Goles convertidos"] < locales.loc[i,"Goles recibidos"]:
        locales.loc[i,"Perdidos"] = 1    

locales

,Equipo,Resultado,Rival,Goles convertidos,Goles recibidos,Puntos,Perdidos,Ganados,Empatados
0,Manlleu,0-1,Granollers,0,1,0.0,1.0,NaN,NaN
1,Vilafranca,4-5,Terrassa,4,5,0.0,1.0,NaN,NaN
2,Olot,5-0,Granollers,5,0,3.0,NaN,1.0,NaN
3,Vilafranca,5-5,Manlleu,5,5,1.0,NaN,NaN,1.0
4,Cornellà,5-1,Prat,5,1,3.0,NaN,1.0,NaN
...,...,...,...,...,...,...,...,...,...
495,Nàstic de Tarragona,1-3,Olot,1,3,0.0,1.0,NaN,NaN
496,Badalona,5-4,Prat,5,4,3.0,NaN,1.0,NaN
497,Olot,4-5,Llagostera,4,5,0.0,1.0,NaN,NaN
498,FC Barcelona,3-1,Cornellà,3,1,3.0,NaN,1.0,NaN
499,Olot,0-5,Granollers,0,5,0.0,1.0,NaN,NaN

In [380]:
# hago la tabla de visitantes

visitantes = df_historic_partits[["Visitante", "Resultado", "Local", "Goles visitante", "Goles local", "Puntos visitante"]]
visitantes = visitantes.rename(columns={"Visitante":"Equipo", "Local":"Rival", "Goles local":"Goles recibidos",
                                  "Goles visitante": "Goles convertidos", "Puntos visitante":"Puntos"})
# invierto el resultado para que tenga sentido:
for i in range(0,len(visitantes)):       
    resultado = visitantes.loc[i,"Resultado"]
    visitantes.loc[i,"Resultado"] = resultado[::-1]

#calculo la cantidad de partidos ganados, empatados y perdidos
for i in range(0,len(locales)):       
    # Caso 1: partidos ganados por local
    if visitantes.loc[i,"Goles convertidos"] > visitantes.loc[i,"Goles recibidos"]:
        visitantes.loc[i,"Ganados"] = 1
    #caso 2: partidos empatados
    elif visitantes.loc[i,"Goles convertidos"] == visitantes.loc[i,"Goles recibidos"]:
        visitantes.loc[i,"Empatados"] = 1
    #caso 3: partidas perdidos por local
    elif visitantes.loc[i,"Goles convertidos"] < visitantes.loc[i,"Goles recibidos"]:
        visitantes.loc[i,"Perdidos"] = 1    
visitantes

,Equipo,Resultado,Rival,Goles convertidos,Goles recibidos,Puntos,Ganados,Perdidos,Empatados
0,Granollers,1-0,Manlleu,1,0,3.0,1.0,NaN,NaN
1,Terrassa,5-4,Vilafranca,5,4,3.0,1.0,NaN,NaN
2,Granollers,0-5,Olot,0,5,0.0,NaN,1.0,NaN
3,Manlleu,5-5,Vilafranca,5,5,1.0,NaN,NaN,1.0
4,Prat,1-5,Cornellà,1,5,0.0,NaN,1.0,NaN
...,...,...,...,...,...,...,...,...,...
495,Olot,3-1,Nàstic de Tarragona,3,1,3.0,1.0,NaN,NaN
496,Prat,4-5,Badalona,4,5,0.0,NaN,1.0,NaN
497,Llagostera,5-4,Olot,5,4,3.0,1.0,NaN,NaN
498,Cornellà,1-3,FC Barcelona,1,3,0.0,NaN,1.0,NaN
499,Granollers,5-0,Olot,5,0,3.0,1.0,NaN,NaN

In [381]:
# tabla con todos los datos
locales_visitantes = pd.concat([locales, visitantes], ignore_index= True)
locales_visitantes

,Equipo,Resultado,Rival,Goles convertidos,Goles recibidos,Puntos,Perdidos,Ganados,Empatados
0,Manlleu,0-1,Granollers,0,1,0.0,1.0,NaN,NaN
1,Vilafranca,4-5,Terrassa,4,5,0.0,1.0,NaN,NaN
2,Olot,5-0,Granollers,5,0,3.0,NaN,1.0,NaN
3,Vilafranca,5-5,Manlleu,5,5,1.0,NaN,NaN,1.0
4,Cornellà,5-1,Prat,5,1,3.0,NaN,1.0,NaN
...,...,...,...,...,...,...,...,...,...
995,Olot,3-1,Nàstic de Tarragona,3,1,3.0,NaN,1.0,NaN
996,Prat,4-5,Badalona,4,5,0.0,1.0,NaN,NaN
997,Llagostera,5-4,Olot,5,4,3.0,NaN,1.0,NaN
998,Cornellà,1-3,FC Barcelona,1,3,0.0,1.0,NaN,NaN
999,Granollers,5-0,Olot,5,0,3.0,NaN,1.0,NaN

In [387]:
# armo las consultas:

resumen = locales_visitantes.groupby(["Equipo"]).agg({"Ganados":"count", "Empatados":"count","Perdidos":"count",
                                                      "Goles convertidos": "sum", "Goles recibidos": "sum",
                                                       "Puntos": "sum"}).sort_values(["Puntos"], ascending=False).reset_index()
resumen

,Equipo,Ganados,Empatados,Perdidos,Goles convertidos,Goles recibidos,Puntos
0,Girona FC,31,3,13,139,94,96.0
1,Llagostera,29,7,20,159,142,94.0
2,Sabadell,26,7,15,141,121,85.0
3,Cornellà,25,7,22,147,146,82.0
4,RCD Espanyol,23,11,21,131,144,80.0
5,Figueres,23,10,23,161,154,79.0
6,Lleida Esportiu,23,6,23,129,133,75.0
7,Terrassa,20,14,23,147,164,74.0
8,FC Barcelona,22,7,15,125,115,73.0
9,Vilafranca,20,12,25,157,172,72.0
10,Reus Deportiu,20,8,16,119,111,68.0
11,Badalona,18,14,16,134,124,68.0
12,Nàstic de Tarragona,20,8,27,130,148,68.0
13,Granollers,21,4,24,122,117,67.0
14,Olot,18,10,26,132,144,64.0
15,Sant Andreu,17,11,25,123,134,62.0
16,Manlleu,16,9,18,106,118,57.0
17,Prat,16,8,21,106,111,56.0
18,Cerdanyola,17,5,28,117,133,56.0
19,Europa,12,5,16,93,93,41.0